name: Java CI with Maven for v2.x

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        export JSWEET_VERBOSE=false
        cd transpiler
        mvn clean install -DskipSigning
	
